"""
Django settings for djangocrud project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e(*&3ei*51to6c+8!&=(=@vk9jqk9igw_w&elp4jx!iid+zrwv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'task',
    'django.contrib.sites',
    'allauth', 
    'allauth.account',
    'allauth.socialaccount',  
    'allauth.socialaccount.providers.google',  
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
)


ROOT_URLCONF = 'djangocrud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangocrud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ==================== CONFIGURACIÓN DE EMAIL ====================

# Para desarrollo: Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'armasyaniel@gmail.com'  # ← CAMBIA ESTO
EMAIL_HOST_PASSWORD = 'abcd efgh ijkl mnop'  # ← CAMBIA ESTO (contraseña de app)
DEFAULT_FROM_EMAIL = 'armasyaniel@gmail.com'
SERVER_EMAIL = 'armasyaniel@gmail.com'

# ==================== CONFIGURACIÓN DE ALLAUTH ====================
# ==================== CONFIGURACIÓN DE ALLAUTH ====================
# ==================== CONFIGURACIÓN DE EMAIL ====================

# Backend para enviar emails reales
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Configuración de Gmail
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# TU EMAIL DE GMAIL (CÁMBIALO)
EMAIL_HOST_USER = 'armasyaniel@gmail.com'  # ← PON TU EMAIL AQUÍ

# CONTRASEÑA DE APLICACIÓN QUE GENERASTE (CÁMBIALA)
EMAIL_HOST_PASSWORD = 'zzlc mddv sttq mpqk'  # ← PON TU CONTRASEÑA DE APP AQUÍ

# Email que aparecerá como remitente
DEFAULT_FROM_EMAIL = 'armasyaniel@gmail.com'  # ← PON TU EMAIL AQUÍ
SERVER_EMAIL = 'armasyaniel@gmail.com'  # ← PON TU EMAIL AQUÍ



SITE_ID = 1

# Redirecciones
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Configuración de cuenta
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*']

# ← CAMBIAR ESTO: De 'none' a 'mandatory'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

# Configuración de verificación de email
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Link válido por 3 días
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Login automático al verificar

# Configuración de Google OAuth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'VERIFIED_EMAIL': True
    }
}

SOCIALACCOUNT_AUTO_SIGNUP = True
# Al final del archivo
GROQ_API_KEY ='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'